name: Update Latest Video

on:
  schedule:
    - cron: '0 * * * *' # Run every hour, adjust as needed

jobs:
  update-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@vv4.1.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: gem install rest-client

    - name: Update Latest Video
      run: ruby .github/scripts/update_latest_video.rb
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: 'UCcEDZeft2x_hYCzSOutrytA'
