name: Update Latest Video

on:
  schedule:
    - cron: '* * * * *' # Run every hour

jobs:
  update-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: gem install rest-client

    - name: Debug - List Files
      run: ls -R

    - name: Debug - Print latest video JSON (before)
      run: cat _data/latest_video.json

    - name: Update Latest Video
      run: ruby .github/scripts/update_latest_video.rb
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        CHANNEL_ID: 'UCcEDZeft2x_hYCzSOutrytA'

    - name: Debug - Print latest video JSON (after)
      run: cat _data/latest_video.json

    - name: add
      run: git add .

    - name: commit
      run: git commit -m"latest video update"
    
    - name: push
      run: git push origin main
